# Task 1: Data Cleaning and Preprocessing

## Objective
The objective of this task is to clean and preprocess a customer sales dataset.

The dataset contains missing values, duplicate records, inconsistent entries,
incorrect data formats, and invalid values.

The cleaned dataset will be prepared for further data analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()

'c:\\Users\\DELL\\OneDrive\\Desktop\\Tasks'

In [3]:
os.listdir()

['cleaned_customer_sales_dataset.csv',
 'customer_sales_dataset.csv',
 'Task1.ipynb',
 'Task2.ipynb']

In [4]:
import pandas as pd

data = [
    ["C001","Aarav",21,"Male","Prayagraj","Laptop",1,45000,"2026-09-01","UPI",45000],
    ["C002","Riya",23,"female","prayagraj","Mobile Phone",2,25000,"01/09/2026","upi",50000],
    ["C003","Aman",25,"M","PRAYAGRAJ ","Headphones",1,1500,"2026/09/02","Credit Card",1500],
    ["C004","Neha",22,"Female","Lucknow","Laptop",1,45000,"02-09-2026","credit card",45000],
    ["C005","Rahul",28,"male","lucknow","Mobile phone",1,25000,"2026-09-03","COD",25000],
    ["C006","Priya",24,"F","Kanpur","Headphones",2,1500,"03/09/2026","Cash on Delivery",3000],
    ["C007","Vikas",150,"Male","Kanpur","Laptop",1,45000,"2026-09-04","UPI",45000],
    ["C008","Anjali",27,"female","kanpur","Mobile Phone",1,25000,"04-09-2026","UPI",25000],
    ["C009","Rohan",26,"M","Varanasi","Headphones",3,1500,"2026-09-05","upi",4500],
    ["C010","Sneha",29,"Female","varanasi","Laptop",1,45000,"05/09/2026","Credit Card",45000],
    ["C011","Karan",31,"Male","Prayagraj","Mobile Phone",2,25000,"2026-09-06","COD",50000],
    ["C012","Pooja",24,"female","Prayagraj ","Headphones",1,1500,"06-09-2026","upi",1500],
    ["C013","Mohit",30,"M","Lucknow","Laptop",1,45000,"2026-09-07","Credit Card",45000],
    ["C014","Simran",22,"Female","lucknow","Mobile phone",2,25000,"07/09/2026","upi",50000],
    ["C015","Nitin",35,"male","Kanpur","Headphones",1,1500,"2026-09-08","Cash on Delivery",1500],
    ["C016","Kavya",None,"F","kanpur","Laptop",1,45000,"08-09-2026","UPI",45000],
    ["C017","Arjun",27,"Male","Varanasi","Mobile Phone",1,25000,"2026-09-09",None,25000],
    ["C018","Isha",23,"female","varanasi","Headphones",2,1500,"09/09/2026","upi",3000],
    ["C019","Dev",32,"M","Prayagraj","Laptop",1,45000,"2026-09-10","Credit Card",45000],
    ["C020","Meera",26,"Female",None,"Mobile Phone",1,25000,"10-09-2026","COD",25000],
    ["C021","Aditya",29,"male","Lucknow","Headphones",None,1500,"2026-09-11","UPI",1500],
    ["C022","Nisha",25,"F","Kanpur","Laptop",1,45000,"11/09/2026","Credit Card",45000],
    ["C023","Varun",33,"Male","PRAYAGRAJ","Mobile phone",2,25000,"2026/09/12","upi",50000],
    ["C024","Tanya",24,"Female","Lucknow","Headphones",1,1500,"12-09-2026","COD",1500],
    ["C025","Yash",28,"M","Kanpur","Laptop",1,45000,"2026-09-13","UPI",45000],
]

columns = [
    "Customer_ID","Customer_Name","Age","Gender","City","Product",
    "Quantity","Price","Purchase_Date","Payment_Method","Total_Amount"
]

df = pd.DataFrame(data, columns=columns)

# Intentional duplicate for Task 1
df = pd.concat([df, df.iloc[[2]]], ignore_index=True)

df.to_csv("customer_sales_dataset.csv", index=False)

print("CSV created successfully!")
print("Shape:", df.shape)

CSV created successfully!
Shape: (26, 11)

In [5]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\DELL\OneDrive\Desktop\Tasks
['cleaned_customer_sales_dataset.csv', 'customer_sales_dataset.csv', 'Task1.ipynb', 'Task2.ipynb']

In [6]:
import os

for root, dirs, files in os.walk(os.path.expanduser("~")):
    if "customer_sales_dataset.csv" in files:
        print(os.path.join(root, "customer_sales_dataset.csv"))

C:\Users\DELL\OneDrive\Desktop\Tasks\customer_sales_dataset.csv
C:\Users\DELL\OneDrive\Documents\customer_sales_dataset.csv

In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\customer_sales_dataset.csv")

df.head()

,Customer_ID,Customer_Name,Age,Gender,City,Product,Quantity,Price,Purchase_Date,Payment_Method,Total_Amount
0,C001,Aarav,21.0,Male,Prayagraj,Laptop,1.0,45000,2026-09-01,UPI,45000
1,C002,Riya,23.0,female,prayagraj,Mobile Phone,2.0,25000,01/09/2026,upi,50000
2,C003,Aman,25.0,M,PRAYAGRAJ,Headphones,1.0,1500,2026/09/02,Credit Card,1500
3,C004,Neha,22.0,Female,Lucknow,Laptop,1.0,₹45000,02-09-2026,credit card,45000
4,C005,Rahul,28.0,male,lucknow,Mobile phone,1.0,25000,2026-09-03,COD,25000

In [8]:
print("Shape of dataset:", df.shape)

Shape of dataset: (26, 11)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     26 non-null     str
 1   Customer_Name   26 non-null     str
 2   Age             25 non-null     float64
 3   Gender          26 non-null     str
 4   City            25 non-null     str
 5   Product         26 non-null     str
 6   Quantity        25 non-null     float64
 7   Price           26 non-null     str
 8   Purchase_Date   26 non-null     str
 9   Payment_Method  25 non-null     str
 10  Total_Amount    26 non-null     int64
dtypes: float64(2), int64(1), str(8)
memory usage: 2.4 KB

In [10]:
df.describe(include="all")

,Customer_ID,Customer_Name,Age,Gender,City,Product,Quantity,Price,Purchase_Date,Payment_Method,Total_Amount
count,26,26,25.000000,26,25,26,25.000000,26,26,25,26.000000
unique,25,25,NaN,6,11,4,NaN,4,25,6,NaN
top,C003,Aman,NaN,M,Kanpur,Laptop,NaN,1500,2026/09/02,UPI,NaN
freq,2,2,NaN,6,5,9,NaN,9,2,6,NaN
mean,NaN,NaN,31.560000,NaN,NaN,NaN,1.320000,NaN,NaN,NaN,27865.384615
std,NaN,NaN,24.940061,NaN,NaN,NaN,0.556776,NaN,NaN,NaN,20579.872542
min,NaN,NaN,21.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1500.000000
25%,NaN,NaN,24.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,3000.000000
50%,NaN,NaN,26.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,35000.000000
75%,NaN,NaN,29.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,45000.000000
max,NaN,NaN,150.000000,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,50000.000000

In [11]:
df.isnull().sum()

Customer_ID       0
Customer_Name     0
Age               1
Gender            0
City              1
Product           0
Quantity          1
Price             0
Purchase_Date     0
Payment_Method    1
Total_Amount      0
dtype: int64

In [12]:
print("Number of duplicate records:", df.duplicated().sum())

Number of duplicate records: 1

In [13]:
df[df.duplicated()]

,Customer_ID,Customer_Name,Age,Gender,City,Product,Quantity,Price,Purchase_Date,Payment_Method,Total_Amount
25,C003,Aman,25.0,M,PRAYAGRAJ,Headphones,1.0,1500,2026/09/02,Credit Card,1500

In [14]:
print("Gender:")
print(df["Gender"].unique())

print("\nCity:")
print(df["City"].unique())

print("\nProduct:")
print(df["Product"].unique())

print("\nPayment Method:")
print(df["Payment_Method"].unique())

Gender:
<StringArray>
['Male', 'female', 'M', 'Female', 'male', 'F']
Length: 6, dtype: str

City:
<StringArray>
[ 'Prayagraj',  'prayagraj', 'PRAYAGRAJ ',    'Lucknow',    'lucknow',
     'Kanpur',     'kanpur',   'Varanasi',   'varanasi', 'Prayagraj ',
          nan,  'PRAYAGRAJ']
Length: 12, dtype: str

Product:
<StringArray>
['Laptop', 'Mobile Phone', 'Headphones', 'Mobile phone']
Length: 4, dtype: str

Payment Method:
<StringArray>
['UPI', 'upi', 'Credit Card', 'credit card', 'COD', 'Cash on Delivery', nan]
Length: 7, dtype: str

In [15]:
text_columns = ["Customer_Name", "Gender", "City", "Product", "Payment_Method"]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

In [16]:
df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "male": "Male",
    "F": "Female",
    "female": "Female"
})

In [17]:
df["City"] = df["City"].str.title()
df["Product"] = df["Product"].str.title()

In [18]:
df["Payment_Method"] = df["Payment_Method"].replace({
    "upi": "UPI",
    "credit card": "Credit Card",
    "Cash on Delivery": "COD"
})

In [19]:
print("Gender:", df["Gender"].unique())
print("City:", df["City"].unique())
print("Product:", df["Product"].unique())
print("Payment Method:", df["Payment_Method"].unique())

Gender: <StringArray>
['Male', 'Female']
Length: 2, dtype: string
City: <StringArray>
['Prayagraj', 'Lucknow', 'Kanpur', 'Varanasi', <NA>]
Length: 5, dtype: string
Product: <StringArray>
['Laptop', 'Mobile Phone', 'Headphones']
Length: 3, dtype: string
Payment Method: <StringArray>
['UPI', 'Credit Card', 'COD', <NA>]
Length: 4, dtype: string

In [20]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [21]:
df.loc[(df["Age"] < 1) | (df["Age"] > 100), "Age"] = np.nan

In [22]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [23]:
print("Minimum Age:", df["Age"].min())
print("Maximum Age:", df["Age"].max())
print("Missing Age:", df["Age"].isnull().sum())

Minimum Age: 21.0
Maximum Age: 35.0
Missing Age: 0

In [24]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [25]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [26]:
print("Missing Quantity:", df["Quantity"].isnull().sum())

Missing Quantity: 0

In [27]:
df["Price"] = (
    df["Price"]
    .astype("string")
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)

In [28]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [29]:
df["Price"] = df["Price"].fillna(df["Price"].median())

In [30]:
print("Missing Quantity:", df["Quantity"].isnull().sum())
print("Missing Price:", df["Price"].isnull().sum())
print("Price data type:", df["Price"].dtype)
print("Quantity data type:", df["Quantity"].dtype)

Missing Quantity: 0
Missing Price: 0
Price data type: Int64
Quantity data type: float64

In [31]:
df["Purchase_Date"] = pd.to_datetime(
    df["Purchase_Date"],
    dayfirst=True,
    errors="coerce"
)

In [32]:
print(df["Purchase_Date"].dtype)
print(df["Purchase_Date"].head())

datetime64[us]
0   2026-01-09
1          NaT
2          NaT
3          NaT
4   2026-03-09
Name: Purchase_Date, dtype: datetime64[us]

In [33]:
df["Purchase_Date"] = pd.to_datetime(
    df["Purchase_Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [34]:
print(df["Purchase_Date"].head())
print(df["Purchase_Date"].isnull().sum())

0   2026-01-09
1          NaT
2          NaT
3          NaT
4   2026-03-09
Name: Purchase_Date, dtype: datetime64[us]
16

In [35]:
import os
print(os.getcwd())

c:\Users\DELL\OneDrive\Desktop\Tasks

In [36]:
import os
print(os.listdir())

['cleaned_customer_sales_dataset.csv', 'customer_sales_dataset.csv', 'Task1.ipynb', 'Task2.ipynb']

In [37]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": ["C001","C002","C003","C004","C005","C006","C007","C008","C009","C010",
                    "C011","C012","C013","C014","C015","C016","C017","C018","C019","C020",
                    "C021","C022","C023","C024","C025","C003"],
    
    "Customer_Name": ["Aarav","Riya","Aman","Neha","Rahul","Priya","Vikas","Anjali","Rohit","Sneha",
                      "Karan","Pooja","Arjun","Simran","Aditya","Meera","Nikhil","Kavya","Saurabh","Isha",
                      "Varun","Naina","Harsh","Divya","Manish","Aman"],
    
    "Age": [21,23,25,22,28,24,150,27,31,26,29,32,35,23,30,np.nan,27,22,34,np.nan,
            25,28,33,24,26,25],
    
    "Gender": ["Male","female","M","Female","male","F","Male","female","Male","Female",
               "male","Female","M","female","Male","Female","male","F","Male","female",
               "M","Female","male","F","Male","M"],
    
    "City": ["Prayagraj","prayagraj","PRAYAGRAJ ","Lucknow","lucknow","Kanpur","kanpur","Varanasi",
             "varanasi","Prayagraj ","Lucknow","KANPUR","Kanpur","Varanasi","Prayagraj",
             "Lucknow","prayagraj","VARANASI","Lucknow",np.nan,"Kanpur","prayagraj ",
             "Varanasi","LUCKNOW","Prayagraj","PRAYAGRAJ"],
    
    "Product": ["Laptop","Mobile Phone","Headphones","Laptop","Mobile phone","Headphones","Laptop",
                "Mobile Phone","Laptop","Headphones","Mobile Phone","Laptop","Headphones","Mobile phone",
                "Laptop","Mobile Phone","Headphones","Laptop","Mobile Phone","Laptop","Headphones",
                "Mobile Phone","Laptop","Headphones","Mobile Phone","Headphones"],
    
    "Quantity": [1,2,1,1,1,2,1,1,2,1,1,1,2,1,1,np.nan,2,1,1,1,
                 np.nan,2,1,1,2,1],
    
    "Price": [45000,25000,1500,"₹45000",25000,1500,45000,25000,45000,1500,
              25000,45000,1500,25000,45000,25000,1500,45000,25000,45000,
              1500,25000,45000,1500,25000,1500],
    
    "Purchase_Date": ["2026-09-01","01/09/2026","2026/09/02","02-09-2026","2026-09-03",
                      "03/09/2026","2026/09/04","04-09-2026","2026-09-05","05/09/2026",
                      "2026/09/06","06-09-2026","2026-09-07","07/09/2026","2026/09/08",
                      "08-09-2026","2026-09-09","09/09/2026","2026/09/10","10-09-2026",
                      "2026-09-11","11/09/2026","2026/09/12","12-09-2026","2026-09-13",
                      "2026/09/02"],
    
    "Payment_Method": ["UPI","upi","Credit Card","credit card","COD","Cash on Delivery","UPI",
                       "upi","Credit Card","credit card","COD","UPI","upi","Credit Card",
                       "COD",np.nan,"credit card","UPI","Cash on Delivery","upi",
                       "Credit Card","COD","UPI","credit card","upi","Credit Card"],
    
    "Total_Amount": [45000,50000,1500,45000,25000,3000,45000,25000,90000,1500,
                     25000,45000,3000,25000,45000,25000,3000,45000,25000,45000,
                     1500,50000,45000,1500,50000,1500]
}

df = pd.DataFrame(data)

df.to_csv("customer_sales_dataset.csv", index=False)

print("Dataset created successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset created successfully!
Rows: 26
Columns: 11

In [38]:
df.head()

,Customer_ID,Customer_Name,Age,Gender,City,Product,Quantity,Price,Purchase_Date,Payment_Method,Total_Amount
0,C001,Aarav,21.0,Male,Prayagraj,Laptop,1.0,45000,2026-09-01,UPI,45000
1,C002,Riya,23.0,female,prayagraj,Mobile Phone,2.0,25000,01/09/2026,upi,50000
2,C003,Aman,25.0,M,PRAYAGRAJ,Headphones,1.0,1500,2026/09/02,Credit Card,1500
3,C004,Neha,22.0,Female,Lucknow,Laptop,1.0,₹45000,02-09-2026,credit card,45000
4,C005,Rahul,28.0,male,lucknow,Mobile phone,1.0,25000,2026-09-03,COD,25000

In [39]:
import os
print(os.listdir())

['cleaned_customer_sales_dataset.csv', 'customer_sales_dataset.csv', 'Task1.ipynb', 'Task2.ipynb']

In [40]:
raw_dates = df["Purchase_Date"].astype("string").str.strip()

df["Purchase_Date"] = pd.to_datetime(
    raw_dates,
    format="mixed",
    errors="coerce"
)

print(df["Purchase_Date"].head())
print("Missing dates:", df["Purchase_Date"].isna().sum())

0   2026-09-01
1   2026-01-09
2   2026-09-02
3   2026-02-09
4   2026-09-03
Name: Purchase_Date, dtype: datetime64[us]
Missing dates: 0

In [41]:
df = pd.read_csv("customer_sales_dataset.csv")

In [42]:
raw_dates = df["Purchase_Date"].astype("string").str.strip()

df["Purchase_Date"] = pd.to_datetime(
    raw_dates,
    format="%Y-%m-%d",
    errors="coerce"
)

mask = df["Purchase_Date"].isna()
df.loc[mask, "Purchase_Date"] = pd.to_datetime(
    raw_dates[mask],
    format="%d/%m/%Y",
    errors="coerce"
)

mask = df["Purchase_Date"].isna()
df.loc[mask, "Purchase_Date"] = pd.to_datetime(
    raw_dates[mask],
    format="%Y/%m/%d",
    errors="coerce"
)

mask = df["Purchase_Date"].isna()
df.loc[mask, "Purchase_Date"] = pd.to_datetime(
    raw_dates[mask],
    format="%d-%m-%Y",
    errors="coerce"
)

print(df["Purchase_Date"].head())
print("Missing dates:", df["Purchase_Date"].isna().sum())

0   2026-09-01
1   2026-09-01
2   2026-09-02
3   2026-09-02
4   2026-09-03
Name: Purchase_Date, dtype: datetime64[us]
Missing dates: 0

In [43]:
df["City"] = df["City"].fillna("Unknown")
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")

print("Missing City:", df["City"].isna().sum())
print("Missing Payment Method:", df["Payment_Method"].isna().sum())

Missing City: 0
Missing Payment Method: 0

In [44]:
df = df.drop_duplicates()

print("Duplicate records:", df.duplicated().sum())
print("Total rows:", len(df))

Duplicate records: 0
Total rows: 26

In [45]:
print(df[df.duplicated(keep=False)])

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, Gender, City, Product, Quantity, Price, Purchase_Date, Payment_Method, Total_Amount]
Index: []

In [46]:
print(df[df["Customer_ID"].duplicated(keep=False)])

   Customer_ID Customer_Name   Age Gender        City     Product  Quantity  \
2         C003          Aman  25.0      M  PRAYAGRAJ   Headphones       1.0
25        C003          Aman  25.0      M   PRAYAGRAJ  Headphones       1.0

   Price Purchase_Date Payment_Method  Total_Amount
2   1500    2026-09-02    Credit Card          1500
25  1500    2026-09-02    Credit Card          1500

In [47]:
df = df.drop_duplicates(subset="Customer_ID", keep="first")

print("Duplicate Customer IDs:", df["Customer_ID"].duplicated().sum())
print("Total rows:", len(df))

Duplicate Customer IDs: 0
Total rows: 25

In [48]:
df["Price"] = (
    df["Price"]
    .astype("string")
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [49]:
df["Total_Amount"] = df["Quantity"] * df["Price"]

print(df[["Customer_ID", "Quantity", "Price", "Total_Amount"]].head())

  Customer_ID  Quantity  Price  Total_Amount
0        C001       1.0  45000       45000.0
1        C002       2.0  25000       50000.0
2        C003       1.0   1500        1500.0
3        C004       1.0  45000       45000.0
4        C005       1.0  25000       25000.0

In [50]:
print("Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Shape: (25, 11)

Missing Values:
Customer_ID       0
Customer_Name     0
Age               2
Gender            0
City              0
Product           0
Quantity          2
Price             0
Purchase_Date     0
Payment_Method    0
Total_Amount      2
dtype: int64

Duplicate Records:
0

Data Types:
Customer_ID                  str
Customer_Name                str
Age                      float64
Gender                       str
City                         str
Product                      str
Quantity                 float64
Price                      Int64
Purchase_Date     datetime64[us]
Payment_Method               str
Total_Amount             Float64
dtype: object

In [51]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df.loc[(df["Age"] < 1) | (df["Age"] > 100), "Age"] = np.nan
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

df["Total_Amount"] = df["Quantity"] * df["Price"]

In [52]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nShape:", df.shape)

Missing Values:
Customer_ID       0
Customer_Name     0
Age               0
Gender            0
City              0
Product           0
Quantity          0
Price             0
Purchase_Date     0
Payment_Method    0
Total_Amount      0
dtype: int64

Duplicate Records:
0

Shape: (25, 11)

In [53]:
df.to_csv("cleaned_customer_sales_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [54]:
import os
print(os.listdir())

['cleaned_customer_sales_dataset.csv', 'customer_sales_dataset.csv', 'Task1.ipynb', 'Task2.ipynb']

##### Conclusion

In this task, the customer sales dataset was successfully cleaned and preprocessed using Python and Pandas. The dataset was inspected for missing values, duplicate records, inconsistent entries, invalid age values, and incorrect data formats.

The missing values were handled, duplicate records were removed, text values were standardized, prices and quantities were converted into proper numeric formats, and purchase dates were converted into a consistent date format. The Total Amount column was also recalculated using Quantity × Price.

After preprocessing, the final dataset contained **25 rows and 11 columns**, with **no missing values and no duplicate records**. The cleaned dataset was saved as `cleaned_customer_sales_dataset.csv`.

This preprocessing step makes the dataset ready for further analysis and visualization.